--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_interface_theme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_interface_theme (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    active boolean NOT NULL,
    title character varying(50) NOT NULL,
    title_visible boolean NOT NULL,
    logo character varying(100) NOT NULL,
    logo_visible boolean NOT NULL,
    css_header_background_color character varying(10) NOT NULL,
    title_color character varying(10) NOT NULL,
    css_header_text_color character varying(10) NOT NULL,
    css_header_link_color character varying(10) NOT NULL,
    css_header_link_hover_color character varying(10) NOT NULL,
    css_module_background_color character varying(10) NOT NULL,
    css_module_text_color character varying(10) NOT NULL,
    css_module_link_color character varying(10) NOT NULL,
    css_module_link_hover_color character varying(10) NOT NULL,
    css_module_rounded_corners boolean NOT NULL,
    css_generic_link_color character varying(10) NOT NULL,
    css_generic_link_hover_color character varying(10) NOT NULL,
    css_save_button_background_color character varying(10) NOT NULL,
    css_save_button_background_hover_color character varying(10) NOT NULL,
    css_save_button_text_color character varying(10) NOT NULL,
    css_delete_button_background_color character varying(10) NOT NULL,
    css_delete_button_background_hover_color character varying(10) NOT NULL,
    css_delete_button_text_color character varying(10) NOT NULL,
    list_filter_dropdown boolean NOT NULL,
    related_modal_active boolean NOT NULL,
    related_modal_background_color character varying(10) NOT NULL,
    related_modal_rounded_corners boolean NOT NULL,
    logo_color character varying(10) NOT NULL,
    recent_actions_visible boolean NOT NULL,
    favicon character varying(100) NOT NULL,
    related_modal_background_opacity character varying(5) NOT NULL,
    env_name character varying(50) NOT NULL,
    env_visible_in_header boolean NOT NULL,
    env_color character varying(10) NOT NULL,
    env_visible_in_favicon boolean NOT NULL,
    related_modal_close_button_visible boolean NOT NULL,
    language_chooser_active boolean NOT NULL,
    language_chooser_display character varying(10) NOT NULL,
    list_filter_sticky boolean NOT NULL,
    form_pagination_sticky boolean NOT NULL,
    form_submit_sticky boolean NOT NULL,
    css_module_background_selected_color character varying(10) NOT NULL,
    css_module_link_selected_color character varying(10) NOT NULL,
    logo_max_height smallint NOT NULL,
    logo_max_width smallint NOT NULL,
    foldable_apps boolean NOT NULL,
    language_chooser_control character varying(20) NOT NULL,
    list_filter_highlight boolean NOT NULL,
    list_filter_removal_links boolean NOT NULL,
    show_fieldsets_as_tabs boolean NOT NULL,
    show_inlines_as_tabs boolean NOT NULL,
    CONSTRAINT admin_interface_theme_logo_max_height_check CHECK ((logo_max_height >= 0)),
    CONSTRAINT admin_interface_theme_logo_max_width_check CHECK ((logo_max_width >= 0))
);


ALTER TABLE public.admin_interface_theme OWNER TO postgres;

--
-- Name: admin_interface_theme_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_interface_theme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_interface_theme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: emporium_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_account (
    id bigint NOT NULL,
    user_name character varying(125),
    first_name character varying(65),
    last_name character varying(65),
    electronic_mail character varying(65),
    user_id bigint
);


ALTER TABLE public.emporium_account OWNER TO postgres;

--
-- Name: emporium_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_delivery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_delivery (
    id bigint NOT NULL,
    phone_number character varying(11),
    purok_name character varying(50),
    barangay_name character varying(50),
    municipality_name character varying(50),
    delivery_date date NOT NULL,
    account_id bigint,
    purchase_id bigint
);


ALTER TABLE public.emporium_delivery OWNER TO postgres;

--
-- Name: emporium_delivery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_delivery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_delivery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_item (
    id bigint NOT NULL,
    item_name character varying(125),
    item_description text,
    item_price numeric(5,2) NOT NULL,
    item_quantity integer,
    item_image character varying(100),
    item_catalogue character varying(125)
);


ALTER TABLE public.emporium_item OWNER TO postgres;

--
-- Name: emporium_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_order (
    id bigint NOT NULL,
    purchase_amount integer,
    purchase_date timestamp with time zone NOT NULL,
    item_id bigint,
    purchase_id bigint
);


ALTER TABLE public.emporium_order OWNER TO postgres;

--
-- Name: emporium_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_order_view; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.emporium_order_view AS
 SELECT emporium_order.id,
    emporium_order.purchase_amount,
    emporium_order.purchase_date,
    emporium_order.item_id,
    emporium_order.purchase_id
   FROM public.emporium_order;


ALTER TABLE public.emporium_order_view OWNER TO postgres;

--
-- Name: emporium_purchase; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_purchase (
    id bigint NOT NULL,
    order_date timestamp with time zone NOT NULL,
    order_completion boolean,
    order_voucher character varying(20),
    order_status character varying(20),
    account_id bigint
);


ALTER TABLE public.emporium_purchase OWNER TO postgres;

--
-- Name: emporium_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_purchase_view; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.emporium_purchase_view AS
 SELECT emporium_purchase.id,
    emporium_purchase.order_date,
    emporium_purchase.order_completion,
    emporium_purchase.order_voucher,
    emporium_purchase.order_status,
    emporium_purchase.account_id
   FROM public.emporium_purchase;


ALTER TABLE public.emporium_purchase_view OWNER TO postgres;

--
-- Name: emporium_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_customer boolean NOT NULL,
    is_analyst boolean NOT NULL
);


ALTER TABLE public.emporium_user OWNER TO postgres;

--
-- Name: emporium_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.emporium_user_groups OWNER TO postgres;

--
-- Name: emporium_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emporium_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emporium_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.emporium_user_user_permissions OWNER TO postgres;

--
-- Name: emporium_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emporium_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emporium_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_interface_theme admin_interface_theme_name_30bda70f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_interface_theme
    ADD CONSTRAINT admin_interface_theme_name_30bda70f_uniq UNIQUE (name);


--
-- Name: admin_interface_theme admin_interface_theme_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_interface_theme
    ADD CONSTRAINT admin_interface_theme_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: emporium_account emporium_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_account
    ADD CONSTRAINT emporium_account_pkey PRIMARY KEY (id);


--
-- Name: emporium_account emporium_account_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_account
    ADD CONSTRAINT emporium_account_user_id_key UNIQUE (user_id);


--
-- Name: emporium_delivery emporium_delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_delivery
    ADD CONSTRAINT emporium_delivery_pkey PRIMARY KEY (id);


--
-- Name: emporium_item emporium_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_item
    ADD CONSTRAINT emporium_item_pkey PRIMARY KEY (id);


--
-- Name: emporium_order emporium_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_order
    ADD CONSTRAINT emporium_order_pkey PRIMARY KEY (id);


--
-- Name: emporium_purchase emporium_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_purchase
    ADD CONSTRAINT emporium_purchase_pkey PRIMARY KEY (id);


--
-- Name: emporium_user_groups emporium_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_groups
    ADD CONSTRAINT emporium_user_groups_pkey PRIMARY KEY (id);


--
-- Name: emporium_user_groups emporium_user_groups_user_id_group_id_60912225_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_groups
    ADD CONSTRAINT emporium_user_groups_user_id_group_id_60912225_uniq UNIQUE (user_id, group_id);


--
-- Name: emporium_user emporium_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user
    ADD CONSTRAINT emporium_user_pkey PRIMARY KEY (id);


--
-- Name: emporium_user_user_permissions emporium_user_user_permi_user_id_permission_id_676d8d7d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_user_permissions
    ADD CONSTRAINT emporium_user_user_permi_user_id_permission_id_676d8d7d_uniq UNIQUE (user_id, permission_id);


--
-- Name: emporium_user_user_permissions emporium_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_user_permissions
    ADD CONSTRAINT emporium_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: emporium_user emporium_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user
    ADD CONSTRAINT emporium_user_username_key UNIQUE (username);


--
-- Name: admin_interface_theme_name_30bda70f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX admin_interface_theme_name_30bda70f_like ON public.admin_interface_theme USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: emporium_ac_user_na_96507b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_ac_user_na_96507b_idx ON public.emporium_account USING btree (user_name);


--
-- Name: emporium_de_phone_n_ca7270_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_de_phone_n_ca7270_idx ON public.emporium_delivery USING btree (phone_number);


--
-- Name: emporium_delivery_account_id_0bb0f747; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_delivery_account_id_0bb0f747 ON public.emporium_delivery USING btree (account_id);


--
-- Name: emporium_delivery_purchase_id_98264ec9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_delivery_purchase_id_98264ec9 ON public.emporium_delivery USING btree (purchase_id);


--
-- Name: emporium_it_item_na_a6175a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_it_item_na_a6175a_idx ON public.emporium_item USING btree (item_name);


--
-- Name: emporium_order_item_id_f7cada88; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_order_item_id_f7cada88 ON public.emporium_order USING btree (item_id);


--
-- Name: emporium_order_purchase_id_ed428665; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_order_purchase_id_ed428665 ON public.emporium_order USING btree (purchase_id);


--
-- Name: emporium_purchase_account_id_26ae7ce5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_purchase_account_id_26ae7ce5 ON public.emporium_purchase USING btree (account_id);


--
-- Name: emporium_user_groups_group_id_2871082c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_user_groups_group_id_2871082c ON public.emporium_user_groups USING btree (group_id);


--
-- Name: emporium_user_groups_user_id_4318836c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_user_groups_user_id_4318836c ON public.emporium_user_groups USING btree (user_id);


--
-- Name: emporium_user_user_permissions_permission_id_d7674f79; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_user_user_permissions_permission_id_d7674f79 ON public.emporium_user_user_permissions USING btree (permission_id);


--
-- Name: emporium_user_user_permissions_user_id_625371fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_user_user_permissions_user_id_625371fb ON public.emporium_user_user_permissions USING btree (user_id);


--
-- Name: emporium_user_username_8fbd5f47_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX emporium_user_username_8fbd5f47_like ON public.emporium_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_emporium_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_emporium_user_id FOREIGN KEY (user_id) REFERENCES public.emporium_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_account emporium_account_user_id_9466323c_fk_emporium_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_account
    ADD CONSTRAINT emporium_account_user_id_9466323c_fk_emporium_user_id FOREIGN KEY (user_id) REFERENCES public.emporium_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_delivery emporium_delivery_account_id_0bb0f747_fk_emporium_account_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_delivery
    ADD CONSTRAINT emporium_delivery_account_id_0bb0f747_fk_emporium_account_id FOREIGN KEY (account_id) REFERENCES public.emporium_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_delivery emporium_delivery_purchase_id_98264ec9_fk_emporium_purchase_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_delivery
    ADD CONSTRAINT emporium_delivery_purchase_id_98264ec9_fk_emporium_purchase_id FOREIGN KEY (purchase_id) REFERENCES public.emporium_purchase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_order emporium_order_item_id_f7cada88_fk_emporium_item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_order
    ADD CONSTRAINT emporium_order_item_id_f7cada88_fk_emporium_item_id FOREIGN KEY (item_id) REFERENCES public.emporium_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_order emporium_order_purchase_id_ed428665_fk_emporium_purchase_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_order
    ADD CONSTRAINT emporium_order_purchase_id_ed428665_fk_emporium_purchase_id FOREIGN KEY (purchase_id) REFERENCES public.emporium_purchase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_purchase emporium_purchase_account_id_26ae7ce5_fk_emporium_account_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_purchase
    ADD CONSTRAINT emporium_purchase_account_id_26ae7ce5_fk_emporium_account_id FOREIGN KEY (account_id) REFERENCES public.emporium_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_user_groups emporium_user_groups_group_id_2871082c_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_groups
    ADD CONSTRAINT emporium_user_groups_group_id_2871082c_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_user_groups emporium_user_groups_user_id_4318836c_fk_emporium_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_groups
    ADD CONSTRAINT emporium_user_groups_user_id_4318836c_fk_emporium_user_id FOREIGN KEY (user_id) REFERENCES public.emporium_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_user_user_permissions emporium_user_user_p_permission_id_d7674f79_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_user_permissions
    ADD CONSTRAINT emporium_user_user_p_permission_id_d7674f79_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: emporium_user_user_permissions emporium_user_user_p_user_id_625371fb_fk_emporium_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emporium_user_user_permissions
    ADD CONSTRAINT emporium_user_user_p_user_id_625371fb_fk_emporium_ FOREIGN KEY (user_id) REFERENCES public.emporium_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

